# Generated by Django 3.0.3 on 2020-03-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0003_auto_20200227_0914'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='me',
        ),
    ]
