# Generated by Django 3.0.3 on 2020-03-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0004_auto_20200303_1537'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
